/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.raymank26.csvsh

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import org.slf4j.LoggerFactory
import java.io.PrintWriter
import java.io.StringWriter

private val LOG = LoggerFactory.getLogger("App")

fun main(args: Array<String>) {
    LOG.info("Application has started")
    Cmd().main(args)
}

class Cmd : CliktCommand() {

    private val cmd: String? by option("-c", "--cmd", help = "SQL statement to run", metavar = "CMD")
    private val version: Boolean by option("-v", "--version", help = "Show version").flag()

    override fun run() {
        when {
            version -> {
                val version = BuildPropertiesParser().parse().version
                echo(version)
            }
            cmd != null -> {
                val stringWriter = StringWriter()
                ReplInterpreter().runOnce(cmd!!, PrintWriter(stringWriter))
                echo(stringWriter.toString(), trailingNewline = false)
            }
            else -> {
                ReplInterpreter().runLoop()
            }
        }
    }
}
