/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.raymank26.csvsh

import org.slf4j.LoggerFactory

private val LOG = LoggerFactory.getLogger("App")

fun main(args: Array<String>) {
    LOG.info("Application has started")
    ReplInterpreter().run()
}
